spring:
  application:
    name: cardRecord
  datasource:
    url: jdbc:mysql://120.26.167.3:3306/cardRecord
    username: thaddeus
    password: fsy0809
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**.xml

server:
  port: 8088

logging:
  level:
    com:
      thaddeus:
        server:
          mapper: debug
          service: info
          controller: info

wechat:
  miniapp:
    jscode2session-url: https://api.weixin.qq.com/sns/jscode2session
    appid: wxe0882ca2e1fc1ba9
    secret: cede831eb1571f6bf30820f9844890b0
    grant-type: authorization_code

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天 2592000 ，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-32
  # 是否输出操作日志
  is-log: true



